[package]
name = "compute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.13.0"
pest = "2.7.14"
pest_derive = "2.7.14"
bincode = "1.3.3"
sha2 = "0.10.8"
serde = { version = "1.0.210", features = ["derive"] }


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
incremental = false
strip = true

[profile.release.package."*"]
opt-level = 3
debug = false
codegen-units = 1
incremental = false
