[package]
name = "compute"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.14.0"
pest = "2.7.14"
pest_derive = "2.7.14"
bincode = "1.3.3"
serde = { version = "1.0.215", features = ["derive"] }
blake3 = "1.5.5"
const-currying = "0.0.5"
branches = "0.1.3"
unroll = "0.1.5"
##libloading = "0.8.6"
##goblin = "0.9.2"
##rayon = "1.10.0"
##gxhash = { version = "3.4.1" }
snmalloc-rs = { version = "0.3.7", features = ["native-cpu", "lto", "usecxx17"] }
internment = { version = "0.8.6", features = ["serde"] }
#compact_str = { version = "0.8.0", features = ["serde"] }
colored = "3.0.0"
i48 = "1.2.0"


[profile.dev]
panic = 'abort'
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
strip = true
debug-assertions = false

[profile.release.package."*"]
opt-level = 3
debug = false
codegen-units = 1
incremental = false
strip = true

[profile.debugrelease]
inherits = "release"
lto = true
strip = false
codegen-units = 1
opt-level = 3
debug = 2
debug-assertions = false
panic = "abort"
rpath = true

[profile.debugrelease.package."*"]
opt-level = 3
debug = 2
codegen-units = 1
