[package]
name = "turbo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.8"
pest_derive = { version = "2.7.8", features = ["grammar-extras"] }
lazy_static = "1.4.0"
regex = "1.10.3"
once_cell = "1.19.0"
colored = "2.1.0"

