[package]
name = "compute"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
bincode = "1.3.3"
serde = { version = "1.0.215", features = ["derive"] }
blake3 = "1.5.5"
##libloading = "0.8.6"
##goblin = "0.9.2"
##rayon = "1.10.0"
internment = { version = "0.8.6", features = ["serde"] }
colored = "3.0.0"
concat-string = "1.0.1"
likely_stable = "0.1.3"
mimalloc = "0.1.43"
heapless = "0.8.0"


[profile.dev]
panic = 'abort'
debug-assertions = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
strip = true
debug-assertions = false

[profile.release.package."*"]
opt-level = 3
debug = false
codegen-units = 1
incremental = false
strip = true

[profile.debugrelease]
inherits = "release"
lto = true
strip = false
codegen-units = 1
opt-level = 3
debug = 2
debug-assertions = false
panic = "abort"
rpath = true

[profile.debugrelease.package."*"]
opt-level = 3
debug = 2
codegen-units = 1
