func test(x) {
return x<=20;
}

func main() {
let count = 0;
// let test = count+1000000;
// print(test(20));
// while count < test {
// //     print(count);
//     count = count+1;
// }
print(count);
let limit = 1000000;
let result = 1;
while count < limit {
    result = result * 2;
    if result > 1000000 {
        result = result % 1000000;
    }
    count = count + 1;
}
print("Final result: ".uppercase()+str(result));
let x = [0];
x = x.insert(0, 1+1);
print(x);
}